# to_macro.py
import FreeCAD
import FreeCADGui
import Part
from PySide import QtCore
from freecad.toSketch import vector_utils as vu

class ToMacroFeature:
    """Exports a SketchObject to a FreeCAD macro (.FCMacro)"""

    def Activated(self):
        for sel in FreeCADGui.Selection.getSelection():
            if sel.TypeId != 'Sketcher::SketchObject':
                print("Please select a SketchObject.")
                continue
            self.action_to_macro(sel)

    def action_to_macro(self, sketch):
        geo = sketch.Geometry
        param = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Macro")
        path = param.GetString("MacroPath", "") + "/"
        path = path.replace("\\", "/")
        macro_file = path + sketch.Label + '.FCMacro'

        print(f"Writing macro: {macro_file}")
        with open(macro_file, 'w') as fp:
            fp.write("# Generated by toSketch Macro Feature\n")
            fp.write("sketch = FreeCAD.ActiveDocument.ActiveObject\n")
            fp.write("newSketch = True\n")
            fp.write("if sketch is not None:\n")
            fp.write("    if hasattr(sketch,'TypeId'):\n")
            fp.write("        if sketch.TypeId == 'Sketcher::SketchObject':\n")
            fp.write("            newSketch = False\n")
            fp.write("if newSketch:\n")
            fp.write("    sketch = FreeCAD.ActiveDocument.addObject('Sketcher::SketchObject','Sketch')\n")
            fp.write(f"print('Active Sketch: {sketch.Label}')\n")

            for g in geo:
                type_id = g.TypeId
                if type_id == 'Part::GeomLineSegment':
                    fp.write('sketch.addGeometry(Part.LineSegment(')
                    vu.wrt_vector(fp, g.StartPoint, True)
                    vu.wrt_vector(fp, g.EndPoint, False)
                    fp.write('), False)\n')
                elif type_id == 'Part::GeomArcOfCircle':
                    fp.write('sketch.addGeometry(Part.ArcOfCircle(Part.Circle(')
                    vu.wrt_vector(fp, g.Center, True)
                    fp.write('FreeCAD.Vector(0,0,1),'+str(g.Radius)+'),')
                    fp.write(f"{vu.get_radians(g.StartPoint, g.Center)},")
                    fp.write(f"{vu.get_radians(g.EndPoint, g.Center)}), False)\n")
                elif type_id == 'Part::GeomCircle':
                    fp.write('sketch.addGeometry(Part.Circle(')
                    vu.wrt_vector(fp, g.Center, True)
                    vu.wrt_identity(fp, True)
                    fp.write(f"{g.Radius}), False)\n")
                elif type_id == 'Part::GeomPoint':
                    fp.write(f'sketch.addGeometry(Part.Point(FreeCAD.Vector({g.X},{g.Y},{g.Z})), False)\n')
                elif type_id == 'Part::GeomBSplineCurve':
                    fp.write('sketch.addGeometry(Part.BSplineCurve(')
                    vu.wrt_vector_list(fp, g.getPoles())
                    fp.write(f', None, None, False, {g.NbPoles}, None, False), False)\n')

            # Constraints
            for c in sketch.Constraints:
                ctype = c.Type
                if ctype == 'Coincident':
                    fp.write(f'sketch.addConstraint(Sketcher.Constraint("Coincident",{c.First},{c.FirstPos},{c.Second},{c.SecondPos}))\n')
                elif ctype == 'Horizontal':
                    fp.write(f'sketch.addConstraint(Sketcher.Constraint("Horizontal",{c.First}))\n')
                elif ctype == 'Vertical':
                    fp.write(f'sketch.addConstraint(Sketcher.Constraint("Vertical",{c.First}))\n')
                elif ctype == 'Equal':
                    fp.write(f'sketch.addConstraint(Sketcher.Constraint("Equal",{c.First},{c.Second}))\n')
                elif ctype == 'Angle':
                    if hasattr(c, 'Second'):
                        fp.write(f'sketch.addConstraint(Sketcher.Constraint("Angle",{c.First},{c.FirstPos},{c.Second},{c.SecondPos},{c.Value}))\n')

        print(f"Macro '{sketch.Label}' written successfully.")

    def IsActive(self):
        return FreeCAD.ActiveDocument is not None

    def GetResources(self):
        return {
            'Pixmap': 'toMacro',
            'MenuText': QtCore.QT_TRANSLATE_NOOP('toMacroFeature', 'To Macro'),
            'ToolTip': QtCore.QT_TRANSLATE_NOOP('toMacroFeature', 'Export sketch as macro')
        }

# Register command
FreeCADGui.addCommand('toMacroCommand', ToMacroFeature())

